### PR TITLE
(#1994) Fixing case sensitivity problem with special header content-length

### LINKED ISSUE #1994: Special headers handling in http is case sensitive
when using a `org.glassfish.grizzly.http.HttpResponsePacket.Builder`, the following calls have different behavior:

* `builder.header("Content-Length", 10)`
* `builder.header("content-length", 10)`

The first one sets the builder field `contentLength` to `10` while the second does not as would be expected.

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Fixes #1994 

Signed-off-by: Sven Diedrichsen <sdiedrichsen@yahoo.de>

### CODE REVIEW

**Review by smillidge — APPROVED** [review]

File: modules/http/src/main/java/org/glassfish/grizzly/http/HttpHeader.java [hunk 1]
```diff
@@ -1147,8 +1147,9 @@ public final T header(String name, String value) {
             if (mimeHeaders == null) {
                 mimeHeaders = new MimeHeaders();
             }
-            mimeHeaders.addValue(name).setString(value);
-            handleSpecialHeaderAdd(name, value);
+            if(!handleSpecialHeaderAdd(name, value)) {
```
Comment (arjantijms) [inline modules/http/src/main/java/org/glassfish/grizzly/http/HttpHeader.java]: Tiny, tiny remark is there should be a space between `if` and `(`.

**Review by arjantijms — APPROVED** [review]
