### PR TITLE
Fix Test scenarios that were failing in JDK 25

### LINKED ISSUE #2259: Test failures appearing in JDK 25
Test failures appearing in JDK 25 by stricter enforcement of networking protocols and resource management in the recent JDK.

- An unexpected "Premature EOF" (End of File) exception
- javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

-----
```
java.io.IOException: Premature EOF
	at java.base/sun.net.www.MeteredStream.justRead(MeteredStream.java:58)
	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:135)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3308)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:279)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:322)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:186)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:183)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:166)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:333)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:400)
	at org.glassfish.grizzly.http.server@4.1.0-SNAPSHOT/org.glassfish.grizzly.http.server.NetworkListenerTest.testGracefulShutdownGracePeriodExpired(NetworkListenerTest.java:244)
```
Since JDK 24 GA, if EOF is encountered during BufferedReader#readLine execution, an IOException may be thrown instead of null.

- https://github.com/openjdk/jdk/blob/jdk-24-ga/src/java.base/share/classes/sun/net/www/MeteredStream.java
- https://github.com/openjdk/jdk/blob/6705a9255d28f351950e7fbca9d05e73942a4e27/src/java.base/share/classes/sun/net/www/MeteredStream.java#L57-L59
- https://bugs.openjdk.org/browse/JDK-8335135 - https://github.com/openjdk/jdk/commit/b6ffb442acb4a222f017868433eff213d9b84ed8

```
[ERROR]   AlpnSupportTest.sslToConnectionMapClearTest:53 » Timeout
[ERROR] org.glassfish.grizzly.http2.AlpnSupportTest.sslToConnectionMapClearTest -- Time elapsed: 10.08 s <<< ERROR!
java.util.concurrent.TimeoutException
	at org.glassfish.grizzly.impl.SafeFutureImpl$Sync.innerGet(SafeFutureImpl.java:324)
	at org.glassfish.grizzly.impl.SafeFutureImpl.get(SafeFutureImpl.java:237)
	at org.glassfish.grizzly.http2.AlpnSupportTest.sslToConnectionMapClearTest(AlpnSupportTest.java:53)
```
Internally, javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate) is occurring.

Consideration should be given to avoiding this error in JDK 25 as well.

### PR DESCRIPTION
**Pull request by carryel**
- #2259 
  + Considered the java.io.IOException: Premature EOF error.
  + Changed to Cipher Suites that support TLS 1.3.
- #2258 
  + (Trivial) Added missing license headers.

All builds and testcases passed successfully on JDK 25.

### CODE REVIEW

**Review by pzygielo — APPROVED** [review]
If this PR fixes some issue - please exercise [Using keywords in issues and pull requests](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) or link it in _Development_ section to automate closing such item.

Also see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests:
> If you reference an issue, pull request, or discussion in a list, the reference will unfurl to show the title and state instead.

Thus difference in formatting
#2260 (not in list)
and
- #2260 


(So funny. Unfurling seems to work in preview of this very comment but not in its final view. Very funny.)

image
image

**Comment by pzygielo** [comment]
#2260

- #2260

**Comment by carryel** [comment]
@pzygielo As always, thank you so much for the information. I've been curious about this. I'll read it and apply it from now on.

File: modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java [hunk 1]
```diff
@@ -241,7 +243,14 @@ public void testGracefulShutdownGracePeriodExpired() throws Exception {
             Future<HttpServer> gracefulFuture = server.shutdown(1, TimeUnit.SECONDS);
 
             final BufferedReader reader = new BufferedReader(new InputStreamReader(c.getInputStream(), Charsets.UTF8_CHARSET));
-            final String content = reader.readLine();
+            String content;
+            try {
+                // null is expected here as the grace period will expire
+                content = reader.readLine();
+            } catch (IOException e) {
+                // or io exception("Premature EOF") is expected here in some high JDKs
```
Comment (OndroMih) [inline modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: Do you know why? This comment is very vague, ideally it should explain why and since which Java version.

File: modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java [hunk 2]
```diff
@@ -241,7 +243,14 @@ public void testGracefulShutdownGracePeriodExpired() throws Exception {
             Future<HttpServer> gracefulFuture = server.shutdown(1, TimeUnit.SECONDS);
 
             final BufferedReader reader = new BufferedReader(new InputStreamReader(c.getInputStream(), Charsets.UTF8_CHARSET));
-            final String content = reader.readLine();
+            String content;
+            try {
+                // null is expected here as the grace period will expire
```
Comment (OndroMih) [inline modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: This comment doesn't make much sense. Is `null` expected on this line? Wouldn't it result in a nullptr exception?
Or it's expected that reader.readLine() throws IOException and then it's OK to set the content to `null`?

I think what you want to say is that `content == null` means the grace period expired. And on newer JDKs the behavior changes - an exception is thrown if grace period expires, instead of returning null.

What about this comment:

```suggestion
                // this should result in null in older JDKs or IOException on newer JDKs as the grace period expires 
```

File: modules/http/src/test/java/org/glassfish/grizzly/http/ParametersTest.java [hunk 3]
```diff
@@ -1,4 +1,5 @@
 /*
+ * Copyright (c) 2025 Contributors to the Eclipse Foundation.
```
Comment (OndroMih) [inline modules/http/src/test/java/org/glassfish/grizzly/http/ParametersTest.java:2]: Reason: 
File was modified earlier without updating the copyright: https://github.com/eclipse-ee4j/glassfish-grizzly/pull/2258/files

File: modules/http/src/main/java/org/glassfish/grizzly/http/util/Parameters.java [hunk 4]
```diff
@@ -1,4 +1,5 @@
 /*
```
Comment (OndroMih) [inline modules/http/src/main/java/org/glassfish/grizzly/http/util/Parameters.java:1]: Reason: 
File was modified earlier without updating the copyright: https://github.com/eclipse-ee4j/glassfish-grizzly/pull/2258/files

File: modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java (hunk 1 above)
Comment (pzygielo) [reply modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: - Isn't this described in linked https://github.com/eclipse-ee4j/glassfish-grizzly/issues/2259?

File: modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java (hunk 2 above)
Comment (carryel) [reply modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: Perhaps I should add a little more explanation. I understand why you were confused. I checked the actual JDK source and noticed that the behavior changed (JDK17 vs. JDK25). However, I didn't find any notices or changelogs regarding this behavior change. However, I was only aware that security and network protocols have become more stringent since JDK 25.

I will try to provide more detailed explanations and supplement the content later.

Comment (pzygielo) [reply modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: > Perhaps I should add a little more explanation. I understand why you were confused. I checked the actual JDK source and noticed that the behavior changed (JDK17 vs. JDK25). 

Maybe this https://bugs.openjdk.org/browse/JDK-8335135 - https://github.com/openjdk/jdk/commit/b6ffb442acb4a222f017868433eff213d9b84ed8

File: modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java (hunk 1 above)
Comment (OndroMih) [reply modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: Thanks. I think we should clarify in the comment, something like "since Java 24 because of stricter enforcement of networking protocols"

File: modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java (hunk 2 above)
Comment (carryel) [reply modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: @OndroMih The `testGracefulShutdownGracePeriodExpired` test does not completely test whether the listener is gracefully shut down.
Graceful shutdown means shutting down when there are no currently active or in-progress http requests and all processing has been completed.

This test generates a shutdown event, delivers it to each listener and registered filter, maintains an unfinished state, and assumes that forced shutdown occurs successfully.

Looking at the test case, Grizzly generates a shutdown event and has a grace period of 1 second.
Grizzly handler first sends a response containing http status and header, waits 2 seconds (expects grace period to expire), and then writes msg.
The core of the test appears to be testing whether or not the shutdown proceeds after the grace period expires after the shutdown event is delivered/propagated through whether or not this msg is received.
In other words, we are verifying that after expiration, shutdown occurs and no msg is received. It seems that the client side probably assumed an EOF situation.

BufferedReader#readLine() is explained as follows:
```
Returns:
A String containing the contents of the line, not including any line-termination characters, or null if the end of the stream has been reached without reading any characters
```
Additionally, there was no change to the intent of returning null in EOF situations.
https://github.com/openjdk/jdk/blob/2c07214d7c075da5dd4a4e872aef29f58cef2bae/src/java.base/share/classes/java/io/BufferedReader.java#L332-L338

However, like the part linked by @pzygielo above, the fill() behavior has been changed to throw an IOException at EOF before returning null.

In a situation where null is returned in the old JDK and an IOException occurs in the new JDK, I briefly thought about changing the test case in a different way to prevent such changes in the JDK, but for comparison purposes, I tried to maintain the existing source as much as possible, so it ended up like this.
I thought it would be less confusing to leave at least a hint rather than just applying the modifications, and I thought it was a test case without much meaning, so I made comments too roughly, which may have caused more confusion.

As you advised, I will submit an edit to leave a more clear comment. :)

Comment (OndroMih) [reply modules/http-server/src/test/java/org/glassfish/grizzly/http/server/NetworkListenerTest.java]: Thanks @carryel, makes perfect sense now! I was maybe a little too pedantic. i just thought it’s good to leave a clear comment in the code for people that come across it in the future :)

**Review by OndroMih — APPROVED** [review]
